export type Platform = "MERCADO_LIVRE" | "SHOPEE" | "AMAZON" | "TIKTOK" | "OUTRO";

/** Oferta alternativa do mesmo produto em outra plataforma (ou outra entrega no ML) */
export interface Offer {
  platform: Platform;
  /** URL de afiliado da oferta */
  url: string;
  /** Preço na plataforma no momento do cadastro — conferir periodicamente */
  price?: number;
  /** Nota curta exibível (ex: "kit 4 cores", "cor preta", "entrega Full") */
  note?: string;
}

export interface LinkConfig {
  /** Usado em /r/:slug — não mude depois de compartilhar */
  slug: string;
  /** URL de afiliado */
  url: string;
  platform: Platform;
  /** Um item pode pertencer a mais de uma categoria */
  categories: string[];
  featured?: boolean;
  /** "Por que eu uso" — 1 frase, voz pessoal */
  review?: string;
  /** ISO date de quando começou a usar (exibido como "uso há X meses") */
  usingSince?: string;
  /** ISO date da última verificação de imagem/título via método do container do botão "Ir para produto" */
  verifiedAt?: string;
  /** Nota livre sobre correções/instabilidades encontradas na verificação */
  verificationNote?: string;
  /**
   * Overrides manuais — o scraper só preenche o que estiver vazio.
   * Obrigatório para Shopee (SPA, não raspável server-side).
   */
  title?: string;
  image?: string;
  description?: string;
  /** Preço atual (com desconto, se houver) — conferir periodicamente, preço do ML varia */
  price?: number;
  /** Preço "de" riscado, quando o item está em promoção */
  originalPrice?: number;
  /** Ofertas do mesmo produto em outras plataformas — o visitante escolhe onde comprar */
  offers?: Offer[];
}

export const SITE_NAME = "Uso e Indico";
export const SITE_TAGLINE = "Só entra aqui o que eu realmente uso";

export const links: LinkConfig[] = [
  {
    slug: "mousepad-couro-volpe",
    url: "https://meli.la/22Jo5tQ",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Elegante e compacto — levo na bolsa pros dias fora do escritório, quando preciso de algo prático sem abrir mão da qualidade.",
    usingSince: "2026-07-01",
    title: "Mouse Pad Couro Legítimo Volpe — Caramelo",
    image: "https://http2.mlstatic.com/D_NQ_NP_957368-MLA110083075342_042026-O.webp",
    price: 29.95,
    originalPrice: 38.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0BM3ZDRRY?tag=dmagno04-20", price: 49.9 },
    ],
  },
  {
    slug: "suporte-celular-360",
    url: "https://meli.la/1s5Waug",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Uma das melhores aquisições que fiz pro escritório — robusto, firme e versátil, com ótimo acabamento.",
    usingSince: "2026-05-13",
    title: "Suporte de Mesa para Celular Alumínio Giratório 360°",
    image: "https://http2.mlstatic.com/D_NQ_NP_645748-MLB102235431879_122025-O.webp",
    price: 33.13,
    originalPrice: 57,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0H4NQZQYQ?tag=dmagno04-20", price: 6.9 },
    ],
  },
  {
    slug: "suporte-notebook-360",
    url: "https://meli.la/1Ua1tQD",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    featured: true,
    review: "Uma das melhores aquisições que fiz pro escritório — robusto, firme e versátil. Comprei um e, dias depois, já comprei o segundo: meus dois notebooks vivem nessas bases hoje.",
    usingSince: "2026-07-01",
    title: "Suporte de Mesa para Notebook 360° Ajustável — Metal",
    image: "https://http2.mlstatic.com/D_NQ_NP_877748-MLB105697398301_012026-O.webp",
    price: 129.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0FTHB3H48?tag=dmagno04-20", price: 85.9 },
    ],
  },
  {
    slug: "apoio-para-pes-ergonomico-descanso-resistente-escr",
    url: "https://meli.la/1Yp2Psx",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Simples, mas cumpre o papel — melhorou bastante as cãibras e o formigamento depois de passar de 8 a 16 horas por dia sentado no escritório.",
    usingSince: "2026-07-01",
    title: "Apoio Para Pés Ergonômico Descanso Resistente Escritório",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_707533-MLB105717403286_012026-V.webp",
    price: 42,
    originalPrice: 59.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B075SKB5DH?tag=dmagno04-20", price: 42.99 },
    ],
  },
  {
    slug: "tripe-para-celular-portatil-1-7m-universal-bastao",
    url: "https://meli.la/27dtUNA",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Prático e fácil de usar — uso em todos os treinos pra gravar com o celular, e evita que ele fique largado no chão da academia.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (o método antigo por alt-text pegava produto desincronizado do destino real do link) — confirmado 2x, estável.",
    title: "Tripé / Bastão Para Celular Portátil Até 1,70 M Com Controle Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_921091-MLB109972041025_042026-V.webp",
    price: 71.07,
    originalPrice: 78.97,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GSCCPL35?tag=dmagno04-20", price: 69.9 },
    ],
  },
  {
    slug: "microfibra-pano-de-limpeza-para-iphone-macbook-cel",
    url: "https://meli.la/2iEaEPx",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Muito bom — pesquisei bastante até achar. Quem tem MacBook sabe como é difícil limpar a tela sem risco, e esse pano faz isso com maestria.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" — produto/imagem antigos não batiam com o destino real do link. Confirmado 2x, estável.",
    title: "Pano De Polimento Limpeza Polishing Para Macbook iPhone iPad",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_904278-MLB75329506010_032024-V.webp",
    price: 29.73,
    originalPrice: 30.97,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DWHQ93T8?tag=dmagno04-20", price: 36.97 },
    ],
  },
  {
    slug: "bolsa-organizadora-cabos-case-estojo-bag-eletronic",
    url: "https://meli.la/2fVdxeZ",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Excelente pra organizar os cabos, tanto nas saídas quanto aqui no escritório — sempre sei onde cada um está.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: preço sem desconto no momento da reverificação",
    title: "Bolsa Organizadora Cabos Case Estojo Bag Eletrônico Grande Cor Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_753655-MLA108762406887_032026-V.webp",
    price: 37.5,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0CCFX2TCV?tag=dmagno04-20", price: 29.9 },
    ],
  },
  {
    slug: "base-suporte-para-pc-notebook-aluminio-portatil-ar",
    url: "https://meli.la/2fpNnyj",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Prático e compacto — uso nas demandas fora do escritório. Foi o único realmente resistente que encontrei; o anterior quebrou em uma semana.",
    title: "Base Suporte Para PC Notebook Alumínio Portátil Articulado Dobrável Tablet Laptop Mesa Hytalux Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_719010-MLA110559363083_042026-V.webp",
    price: 24.15,
    originalPrice: 32.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0H3788T72?tag=dmagno04-20", price: 18.9 },
    ],
  },
  {
    slug: "teclado-ergonomico-sem-fio-logitech-wave-keys-graf",
    url: "https://meli.la/2UAfr3i",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    featured: true,
    review: "Comprei por dois motivos: precisava alternar rápido entre o notebook Windows e o MacBook, e a ergonomia ajuda muito nas horas que passo no computador — ficou bem mais confortável digitar.",
    title: "Teclado Ergonômico Sem Fio Logitech Wave Keys - Grafite Inglês US",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_739716-MLA99453694320_112025-V.webp",
    price: 459,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0CHB9PD4M?tag=dmagno04-20", price: 409.9 },
    ],
  },
  {
    slug: "cabo-thunderbolt-3-ugreen-usb-c-para-hdmi-4k-refor",
    url: "https://meli.la/24JFJL6",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Todo cabo que compro é Ugreen — qualidade que dispensa comentários, sempre cumprem o que prometem.",
    title: "Cabo Thunderbolt 3 Ugreen USB-C Para HDMI 4K Reforçado - Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_852747-MLA99395901500_112025-V.webp",
    price: 124.42,
    originalPrice: 299,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07G5691LJ?tag=dmagno04-20", price: 107.9 },
    ],
  },
  {
    slug: "mousepad-extra-grande-caramelo-90x40cm-deskpad-cou",
    url: "https://meli.la/2DDJo5k",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Uma das melhores aquisições que fiz — muito bonito, dá um charme ao escritório e ainda deixa o mouse livre pra correr sem limites.",
    title: "Mousepad Extra Grande Caramelo 90x40cm Deskpad Couro Antiderrapante Mesa - Kingpad",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_701855-MLA102404626214_122025-V.webp",
    price: 47.49,
    originalPrice: 49.99,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B09HSQBYY1?tag=dmagno04-20", price: 51.14 },
    ],
  },
  {
    slug: "flanela-pano-protecao-tela-e-teclado-apple-macbook",
    url: "https://meli.la/2pRQRVh",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Protege a tela da gordura que fica no teclado e passa pro display quando fecho o MacBook — mantém tudo limpo por mais tempo. Não é qualquer pano que serve pra isso, e esse é o ideal.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\" — era outro item completamente diferente. Reverificado 2x, estável.",
    title: "Flanela Pano Proteção Tela E Teclado Apple Macbook 13 A 16",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_612151-MLB92259649659_092025-V-flanela-pano-proteco-tela-e-teclado-apple-macbook-13-a-16.webp",
    price: 63.79,
    originalPrice: 78.28,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0D9WPRCH8?tag=dmagno04-20", price: 79.97 },
    ],
  },
  {
    slug: "fone-bluetooth-wave-buds-2-tws-azul",
    url: "https://meli.la/2QtskjE",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Fone bom, grave gostoso, o filtro de ruído funciona muito bem — e poder controlar quanto do ambiente eu quero ouvir foi uma baita sacada.",
    title: "Fone Bluetooth Wave Buds 2 TWS Azul",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_811984-MLA99445406304_112025-V.webp",
    price: 234.5,
    originalPrice: 369,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DKJKTPWJ?tag=dmagno04-20", price: 219 },
    ],
  },
  {
    slug: "headset-sem-fio-logitech-zone-vibe-100-grafite",
    url: "https://meli.la/2pC6977",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Estava sofrendo com dores de cabeça pelos fones antigos e precisava de algo leve e confortável sem abrir mão da qualidade de áudio pro trabalho — esse foi o único que bateu tudo isso nas minhas pesquisas.",
    title: "Headset Sem Fio Logitech Zone Vibe 100 - Grafite",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_866279-MLA99513179228_112025-V.webp",
    price: 594.15,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0B8C31YXR?tag=dmagno04-20", price: 529.99 },
    ],
  },
  {
    slug: "capa-para-macbook-air-13-m4-m3-m2-protetor-teclado",
    url: "https://meli.la/2hrMDnX",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Gosto de cuidar bem do que tenho, e esse kit ajuda exatamente nisso — protege o equipamento por completo.",
    title: "Capa Para Macbook Air 13 M4/M3/M2 Protetor Teclado + Bag Transparente Cristal",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_971777-MLA95522187642_102025-V.webp",
    price: 117.23,
    originalPrice: 169.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0FC2JFQ2K?tag=dmagno04-20", price: 88 },
    ],
  },
  {
    slug: "jogo-limpa-telas-pc-notebook-120ml-pano-microfibra",
    url: "https://meli.la/2qBZeEU",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Simples, mas muito funcional — não fico sem.",
    title: "Jogo Limpa Telas PC Notebook 120ml + Pano Microfibra Start",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_727350-MLA100087934009_122025-V.webp",
    price: 22.2,
    originalPrice: 28.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0D5BXC1JL?tag=dmagno04-20", price: 25.78 },
    ],
  },
  {
    slug: "cabo-ugreen-quick-charge-4-0-usb-c-1m-blindado-cin",
    url: "https://meli.la/1nDCC7b",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Todo cabo que compro é Ugreen — qualidade que dispensa comentários, sempre cumprem o que prometem.",
    title: "Cabo Ugreen Quick Charge 4.0 USB-C 1m Blindado - Cinza",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_705800-MLA99599259526_122025-V.webp",
    price: 36.56,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07PP2QHZD?tag=dmagno04-20", price: 48.9 },
    ],
  },
  {
    slug: "ugreen-organizador-cabo-2-metros-40354",
    url: "https://meli.la/1fjWsJZ",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Solução prática pra manter os cabos enrolados e organizados.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Ugreen - Organizador Cabo 2 Metros - 40354 Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_626476-MLB92317605521_092025-V.webp",
    price: 24.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07ZC346SK?tag=dmagno04-20", price: 27.69 },
    ],
  },
  {
    slug: "mouse-sem-fio-logitech-mx-vertical-ergonomico-cinz",
    url: "https://meli.la/1iZ7b9D",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Sentia dores constantes no punho, e esse mouse resolveu — hoje não fico mais sem ele.",
    title: "Mouse Sem Fio Logitech MX Vertical Ergonômico Cinza",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_926785-MLA99858509739_112025-V.webp",
    price: 533.22,
    originalPrice: 579.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07PNKGKBX?tag=dmagno04-20", price: 479.9 },
    ],
  },
  {
    slug: "teclado-sem-fio-signature-k650-grafite-logitech-ci",
    url: "https://meli.la/1Fe9x1H",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Segundo teclado do nosso setup, usado pela minha esposa — muito bom e confortável.",
    title: "Teclado Sem Fio Signature K650 Grafite Logitech Cinza-Escuro",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_780490-MLA99929764499_112025-V.webp",
    price: 241.3,
    originalPrice: 289.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0BK9YLKPM?tag=dmagno04-20", price: 239.18 },
    ],
  },
  {
    slug: "copo-termico-inox-cafe-cha-antivazamento-vacuum",
    url: "https://meli.la/1FStUzP",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    review: "Ajuda muito com o cafezinho — mantém a temperatura ideal e, com a tampa lacrada, não derrama em volta.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Copo Térmico Inox Café Chá Anti-vazamento Vacuum 510ml Azul Coffee",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_642290-MLB113406160621_062026-V.webp",
    price: 27.06,
    originalPrice: 69.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0FFBN14CB?tag=dmagno04-20", price: 49.9 },
    ],
  },
  {
    slug: "kit-limpa-telas-tablet-celular-notebook-computadore",
    url: "https://meli.la/21KQWD3",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Simples, mas muito funcional — não fico sem.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Kit Limpa Telas Tablet Celular Notebook Computadores Vidros",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_806895-MLB73331229509_122023-V.webp",
    price: 30.99,
    originalPrice: 32.99,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DQL9YDG3?tag=dmagno04-20", price: 15.9 },
    ],
  },
  {
    slug: "cinto-de-fitness-com-alavanca-lever-buckle",
    url: "https://meli.la/2bjvGGT",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Essencial pra quem treina perna com carga alta — uso sempre nesses dias.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: método antigo lia texto/imagem soltos que NÃO batiam com o destino real do botão \"Ir para produto\" (bug sério — o Danilo clicou e caiu em produto totalmente diferente). Dado extraído agora do mesmo container do botão, garantindo consistência.",
    title: "Cinturão De Musculação Rudel Rdl2-151 Pride Red",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_898954-MLB78818567107_082024-V-cinturo-de-musculaco-rudel-rdl2-151-pride-red.webp",
    price: 144.65,
    originalPrice: 153.26,
  },
  {
    slug: "straps-fitness-rudel-h-8-204-preto",
    url: "https://meli.la/2Y5nFAX",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Uso com menos frequência, mas é muito bom — ajuda bastante, só não pode virar muleta.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: mesmo bug do \"cinto de fitness\" — texto/imagem antigos não batiam com o destino real do botão \"Ir para produto\". Slug também mudou (era \"silicone-spray\", produto real é outro).",
    title: "Straps Fitness Rudel H-8 204 Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_769827-MLB95776743023_102025-V.webp",
    price: 35.89,
    originalPrice: 37,
  },
  {
    slug: "protetor-de-punho-profissional-crossfit-munhequeir",
    url: "https://meli.la/1Frc4Wu",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Depois de problemas com tendinite, esse protetor me dá segurança e ajuda a evitar lesão.",
    title: "Protetor De Punho Profissional Crossfit Munhequeira Pulso - Rosa",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_721892-MLA99598079074_122025-V.webp",
    price: 33,
    originalPrice: 45.54,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DRMPZ27W?tag=dmagno04-20", price: 40.45 },
    ],
  },
  {
    slug: "kit-3-regata-masculina-americano-canelada-algodao",
    url: "https://meli.la/2iHrnTX",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário"],
    review: "Muito boa — uso todos os dias pra treinar, já estou comprando mais.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (verificação anterior usava alt-text solto, que pegou produto errado). Confirmado 2x, estável.",
    title: "Kit 3 Regata Masculina Americano Canelada Algodão Premium",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_856120-MLB109278068437_032026-V-kit-3-regata-masculina-americano-canelada-algodo-premium.webp",
    price: 59.3,
    originalPrice: 70,
  },
  {
    slug: "cinta-masculina-modeladora-abdominal-ajustavel-ema",
    url: "https://meli.la/233NUCw",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Uso na maioria dos treinos — dá conforto e segurança.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: a página de recomendação do ML troca o produto em destaque até sem reload (algoritmo ativo, não é só cache). A versão anterior (\"Preto GG\") vinha com imagem colagem/promocional que não batia visualmente com o produto. Essa variante \"Lomba Cinza G\" tem foto limpa e bate com o tipo de produto (cinta abdominal).",
    title: "Cinta Modeladora Masculina Abdominal Dupla Compressão Lomba Cinza G",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_801197-MLB108656655278_032026-V.webp",
    price: 86.33,
    originalPrice: 129.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GSHJYPCZ?tag=dmagno04-20", price: 109 },
    ],
  },
  {
    slug: "calca-tactel-masculino-jogger-com-elastano-academi",
    url: "https://meli.la/2gr6yyi",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness", "Vestuário"],
    review: "Me impressionei com a compra — uso quase todo dia, comprei três e hoje só treino com elas.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (verificação anterior pegou variante errada). Confirmado 2x, estável.",
    title: "Calça Tactel Masculino Jogger C/ Elastano Academia Treino",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_692315-MLB87398103458_072025-V-calca-tactel-masculino-jogger-c-elastano-academia-treino.webp",
    price: 36.17,
    originalPrice: 69,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GSCM9KSG?tag=dmagno04-20", price: 35.91 },
    ],
  },
  {
    slug: "munhequeira-musculacao-crossfit-lpo-elastica-alta",
    url: "https://meli.la/1KE8Dgv",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Depois de problemas com tendinite, essa munhequeira me dá segurança e ajuda a evitar lesão.",
    title: "Munhequeira Musculação Crossfit LPO Elástica Alta Compressão - Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_825097-MLA105750783064_022026-V.webp",
    price: 34.44,
    originalPrice: 39.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0CV18Q36K?tag=dmagno04-20", price: 42.9 },
    ],
  },
  {
    slug: "shorts-2-em-1-termico-de-compressao-com-bolso-secr",
    url: "https://meli.la/1skhdLd",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Muito bom — resolve o problema de assaduras e mantém tudo discreto durante o treino.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (verificação anterior pegou variante desincronizada do destino real do link). Confirmado 2x, estável.",
    title: "Shorts 2 Em 1 Térmico De Compressão Bolso Secreto Academia",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_710628-MLB110967764522_052026-V-shorts-2-em-1-termico-de-compresso-bolso-secreto-academia.webp",
    price: 27.77,
    originalPrice: 54.9,
  },
  {
    slug: "relogio-casio-unissex-vintage-aq-230a-1dmq-pratead",
    url: "https://meli.la/2RaFbfu",
    platform: "MERCADO_LIVRE",
    categories: ["Acessórios"],
    review: "Muito bom e elegante.",
    title: "Relógio Casio Unissex Vintage AQ-230A-1DMQ Prateado",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_638064-MLA99489095824_112025-V.webp",
    price: 204.05,
    originalPrice: 454.36,
  },
  {
    slug: "kit-3-regata-oversized-machao-streetwear-lisa-casu",
    url: "https://meli.la/12feN5K",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário"],
    review: "Muito boa — uso sempre por baixo da roupa, como primeira pele.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (mesmo vendedor D2G, imagem/título levemente diferentes do que estava salvo). Confirmado 2x, estável.",
    title: "Kit 3 Regata Oversized Machão Streetwear Lisa Casual Básicas",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_839421-MLB104333596016_012026-V-kit-3-regata-oversized-macho-streetwear-lisa-casual-basicas.webp",
    price: 76.03,
    originalPrice: 143.45,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DHLX9Y9F?tag=dmagno04-20", price: 129.9 },
    ],
  },
  {
    slug: "regata-oversized-masculino-tamanho-grande-basica-l",
    url: "https://meli.la/2bUEgJW",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário"],
    review: "Regata básica que uso bastante no dia a dia, confortável e sem frescura.",
    title: "Regata Oversized Masculino Tamanho Grande Básica Lisa - Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_944768-MLB94446815565_102025-V.webp",
    price: 27,
    originalPrice: 64.14,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0FPNN2PCS?tag=dmagno04-20", price: 56.9 },
    ],
  },
  {
    slug: "suplemento-em-po-panic-150g-adaptogen-uva-com-crea",
    url: "https://meli.la/1USEMLc",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Um dos melhores que já tomei.",
    title: "Suplemento em Pó Panic 150g Adaptogen Uva com Creatina",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_861264-MLA100080909647_122025-V.webp",
    price: 38.8,
    originalPrice: 66,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0B2J5KQB7?tag=dmagno04-20", price: 50 },
    ],
  },
  {
    slug: "pedalboard-luxo-detalhe-em-madeira-universal-com-v",
    url: "https://meli.la/2vup3ow",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Compacto — uso com minha HX e o footswitch, cumpre bem o papel.",
    title: "Pedalboard Luxo Detalhe em Madeira Universal com Velcro Fuhrmann PB5",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_800509-MLA100008009715_122025-V.webp",
    price: 137.75,
    originalPrice: 259.63,
  },
  {
    slug: "footswitch-cabo-50cm-hxstomp-ampero-nux-loop-core",
    url: "https://meli.la/2pDX1qr",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Muito bom, facilitou o uso da HX no meu setup.",
    title: "Footswitch Cabo 50cm HXStomp Ampero NUX Loop Core Vamp FS2NL",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_949576-MLA105895323032_022026-V.webp",
    price: 209,
  },
  {
    slug: "adaptador-p10-macho-p2-femea-estereo-daddario-pwp0",
    url: "https://meli.la/2nADtNJ",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Um dos melhores do mercado — vale investir na durabilidade e qualidade.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/SKU/imagem antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Adaptador P10 Macho P2 Fêmea Estéreo D'Addario PW-P047E",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_895564-MLB84762878925_052025-V.webp",
    price: 123.18,
    originalPrice: 126.99,
  },
  {
    slug: "fita-gaffer-tape-opcao-cores-12mm-x-5mts-fluoresce",
    url: "https://meli.la/23tv7hh",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    review: "Gosto de sinalizar tudo com meus dados, e essa fita é a solução perfeita.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Fita Gaffer Tape Opção Cores 12mm X 5mts Fluorescente Neon",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_817424-MLB93932215678_102025-V-fita-gaffer-tape-opcao-cores-12mm-x-5mts-fluorescente-neon.webp",
    price: 23.45,
    originalPrice: 25.22,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DWB9Y591?tag=dmagno04-20", price: 86.97 },
    ],
  },
  {
    slug: "mesa-dobravel-portatil-palisad-aluminio-branco-90x",
    url: "https://meli.la/1k5kKFp",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    review: "Ótima sacada — super prática, dá pra levar pra qualquer lugar.",
    title: "Mesa Dobrável Portátil Palisad Alumínio Branco 90x60x70cm",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_879613-MLA96146063437_102025-V.webp",
    price: 119.2,
    originalPrice: 149,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0777QNWGL?tag=dmagno04-20", price: 159.9 },
    ],
  },
  {
    slug: "bolsa-bag-mochila-reforcada-alca-para-pedalboard-f",
    url: "https://meli.la/1Sa2yEP",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Muito boa — protege e facilita o transporte do pedalboard.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Bolsa Bag Mochila Reforçada Alça Para Pedalboard Fuhrmann Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_878806-MLB92394662567_092025-V.webp",
    price: 253,
    originalPrice: 302.5,
  },
  {
    slug: "colete-corretor-postural-cervical-alinha-postura",
    url: "https://meli.la/1ALbTSX",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Colete Corretor Postural Para Coluna Cervical Alinha Postura",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_749929-MLB101159772275_122025-V.webp",
    price: 33.7,
    originalPrice: 47.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0F74P6KNR?tag=dmagno04-20", price: 42.99 },
    ],
  },
  {
    slug: "kit-6-regata-americano-canelada-premium-masculina",
    url: "https://meli.la/2XntxKN",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Kit 6 Regata Modelo Americano Canelada Premium Masculina",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_774032-MLB109630771191_032026-V-kit-6-regata-modelo-americano-canelada-premium-masculina.webp",
    price: 117,
    originalPrice: 236.18,
  },
  {
    slug: "kit-apoio-de-copo-4-porta-copos-bambu",
    url: "https://meli.la/2GRtf2r",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Kit Apoio De Copo 4 Porta Copos Bambu Quadrado Redondo",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_951678-MLB114714260747_072026-V.webp",
    price: 27.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GSCVQLCV?tag=dmagno04-20", price: 26.89 },
    ],
  },
  {
    slug: "porta-retrato-duplo-10x15-madeira-decoracao-moldura-foto",
    url: "https://meli.la/2ijTHAV",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Porta Retrato Duplo 10x15 Madeira Decoração Moldura Foto Marrom",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_607838-MLB92880090739_092025-V.webp",
    price: 35.23,
    originalPrice: 55.91,
  },
  {
    slug: "suporte-para-celular-mesa-organizador",
    url: "https://meli.la/1Y6Fwvf",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Suporte Para Celular Mesa Com Organizador",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_761700-MLB93148237428_092025-V.webp",
    price: 79,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GRBYNWM3?tag=dmagno04-20", price: 32.9 },
    ],
  },
];
