export type Platform = "MERCADO_LIVRE" | "SHOPEE" | "AMAZON" | "TIKTOK" | "OUTRO";

/** Oferta alternativa do mesmo produto em outra plataforma (ou outra entrega no ML) */
export interface Offer {
  platform: Platform;
  /** URL de afiliado da oferta */
  url: string;
  /** Preço na plataforma no momento do cadastro — conferir periodicamente */
  price?: number;
  /** Nota curta exibível (ex: "kit 4 cores", "cor preta", "entrega Full") */
  note?: string;
}

export interface LinkConfig {
  /** Usado em /r/:slug — não mude depois de compartilhar */
  slug: string;
  /** URL de afiliado */
  url: string;
  platform: Platform;
  /** Um item pode pertencer a mais de uma categoria */
  categories: string[];
  /**
   * Prateleira do item. "uso" (padrão) = produto que o Danilo usa de verdade,
   * com review em 1ª pessoa. "lista" = ainda não comprou, está na lista de
   * desejo — nunca misturar os dois na mesma listagem sem rótulo visível.
   */
  kind?: "uso" | "lista";
  featured?: boolean;
  /** "Por que eu uso" — 1 frase, voz pessoal */
  review?: string;
  /** ISO date de quando começou a usar (exibido como "uso há X meses") */
  usingSince?: string;
  /** ISO date da última verificação de imagem/título via método do container do botão "Ir para produto" */
  verifiedAt?: string;
  /** Nota livre sobre correções/instabilidades encontradas na verificação */
  verificationNote?: string;
  /**
   * Overrides manuais — o scraper só preenche o que estiver vazio.
   * Obrigatório para Shopee (SPA, não raspável server-side).
   */
  title?: string;
  image?: string;
  description?: string;
  /** Preço atual (com desconto, se houver) — conferir periodicamente, preço do ML varia */
  price?: number;
  /** Preço "de" riscado, quando o item está em promoção */
  originalPrice?: number;
  /** Ofertas do mesmo produto em outras plataformas — o visitante escolhe onde comprar */
  offers?: Offer[];
}

export const SITE_NAME = "Uso e Indico";
export const SITE_TAGLINE = "O que eu uso. E o que eu indico.";

/** Rótulos das duas prateleiras — usados no filtro, nos selos e nos textos */
export const KIND_LABEL = {
  uso: { label: "Eu uso", badge: "EU USO" },
  lista: { label: "Na minha lista", badge: "NA MINHA LISTA" },
} as const;

export const links: LinkConfig[] = [
  {
    slug: "mousepad-couro-volpe",
    url: "https://meli.la/22Jo5tQ",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Elegante e compacto — levo na bolsa pros dias fora do escritório, quando preciso de algo prático sem abrir mão da qualidade.",
    usingSince: "2026-07-01",
    title: "Mouse Pad Couro Legítimo Volpe — Caramelo",
    image: "https://http2.mlstatic.com/D_NQ_NP_957368-MLA110083075342_042026-O.webp",
    price: 29.95,
    originalPrice: 38.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0BM3ZDRRY?tag=dmagno04-20", price: 49.9 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/2qTdudiZ4q", price: 29.8, note: "cor caramelo" },
    ],
  },
  {
    slug: "suporte-celular-360",
    url: "https://meli.la/1s5Waug",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Uma das melhores aquisições que fiz pro escritório — robusto, firme e versátil, com ótimo acabamento.",
    usingSince: "2026-05-13",
    title: "Suporte de Mesa para Celular Alumínio Giratório 360°",
    image: "https://http2.mlstatic.com/D_NQ_NP_645748-MLB102235431879_122025-O.webp",
    price: 33.13,
    originalPrice: 57,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0H4NQZQYQ?tag=dmagno04-20", price: 6.9 },
    ],
  },
  {
    slug: "suporte-notebook-360",
    url: "https://www.amazon.com.br/dp/B0FTHB3H48?tag=dmagno04-20",
    platform: "AMAZON",
    categories: ["Setup"],
    featured: true,
    review: "Uma das melhores aquisições que fiz pro escritório — robusto, firme e versátil. Comprei um e, dias depois, já comprei o segundo: meus dois notebooks vivem nessas bases hoje.",
    usingSince: "2026-07-01",
    verifiedAt: "2026-08-09",
    verificationNote: "ANÚNCIO DO ML MORREU (2026-08-09): meli.la/1Ua1tQD passou a cair na página de listas do perfil, sem botão \"Ir para produto\" — e o item estava EM DESTAQUE na home. Em vez de remover, promovido para a Amazon, que já era oferta cadastrada e continua viva: mesmo produto (aço carbono, base giratória 360°, até 17\"), em estoque e mais barato (R$ 85,90 contra R$ 129,90 no ML). O review segue verdadeiro porque é o mesmo tipo de suporte que ele usa. Slug mantido pra preservar histórico de cliques.",
    title: "Suporte para Notebook até 17\" Aço Carbono — Base Giratória 360°",
    image: "https://m.media-amazon.com/images/I/51wmLU+u3cL._AC_SY450_.jpg",
    price: 85.9,
  },
  {
    slug: "apoio-para-pes-ergonomico-descanso-resistente-escr",
    url: "https://meli.la/1Yp2Psx",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Simples, mas cumpre o papel — melhorou bastante as cãibras e o formigamento depois de passar de 8 a 16 horas por dia sentado no escritório.",
    usingSince: "2026-07-01",
    title: "Apoio Para Pés Ergonômico Descanso Resistente Escritório",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_707533-MLB105717403286_012026-V.webp",
    price: 42,
    originalPrice: 59.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B075SKB5DH?tag=dmagno04-20", price: 42.99 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/2gADiKjCPp", price: 46.9 },
    ],
  },
  {
    slug: "tripe-para-celular-portatil-1-7m-universal-bastao",
    url: "https://meli.la/2faZCb9",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    featured: true,
    review: "Prático e fácil de usar — uso em todos os treinos pra gravar com o celular, e evita que ele fique largado no chão da academia.",
    verifiedAt: "2026-09-18",
    verificationNote: "TROCADO 2026-09-18 a pedido do Danilo, para meli.la/2faZCb9. Verificado 2x pelo método do container do botão \"Ir para produto\" — destino MLB63944629, título/preço/imagem batendo. ATENÇÃO: é outro produto, não o mesmo anúncio mais barato — subiu de R$ 71,07 para R$ 159,08 e virou tripé de 1,8m em alumínio com controle bluetooth. Por isso a oferta Amazon antiga (B0GSCCPL35, R$ 69,90) foi REMOVIDA: ela apontava para o tripé simples anterior e viraria comparação falsa de preço. Slug mantido para preservar histórico de cliques.",
    title: "Basike Tripé / Bastão 1,8m Alumínio 360° com Controle Bluetooth",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_729364-MLA111652938044_062026-V.webp",
    price: 159.08,
    originalPrice: 299,
  },
  {
    slug: "microfibra-pano-de-limpeza-para-iphone-macbook-cel",
    url: "https://meli.la/2iEaEPx",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Muito bom — pesquisei bastante até achar. Quem tem MacBook sabe como é difícil limpar a tela sem risco, e esse pano faz isso com maestria.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" — produto/imagem antigos não batiam com o destino real do link. Confirmado 2x, estável.",
    title: "Pano De Polimento Limpeza Polishing Para Macbook iPhone iPad",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_904278-MLB75329506010_032024-V.webp",
    price: 29.73,
    originalPrice: 30.97,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DWHQ93T8?tag=dmagno04-20", price: 36.97 },
    ],
  },
  {
    slug: "bolsa-organizadora-cabos-case-estojo-bag-eletronic",
    url: "https://meli.la/2zm81nP",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Excelente pra organizar os cabos, tanto nas saídas quanto aqui no escritório — sempre sei onde cada um está.",
    verifiedAt: "2026-07-31",
    verificationNote: "SUBSTITUÍDO 2026-07-31: o anúncio antigo (meli.la/2fVdxeZ, R$ 37,50) saiu do ar — o link de afiliado passou a cair na página de listas do perfil, sem botão \"Ir para produto\". Trocado por anúncio equivalente do mesmo tipo de estojo (MLB26242439, R$ 27,20), com link de afiliado novo verificado 2x pelo método do container. Slug mantido de propósito para não perder o histórico de cliques nem quebrar links já compartilhados. Oferta Amazon revalidada no mesmo dia: em estoque, caiu de R$ 29,90 para R$ 26,90.",
    title: "Estojo Organizador De Cabos E Acessórios Eletrônicos Grande Cor Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_693746-MLA100087490803_122025-V.webp",
    price: 27.2,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0CCFX2TCV?tag=dmagno04-20", price: 26.9 },
    ],
  },
  {
    slug: "base-suporte-para-pc-notebook-aluminio-portatil-ar",
    url: "https://meli.la/2fpNnyj",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Prático e compacto — uso nas demandas fora do escritório. Foi o único realmente resistente que encontrei; o anterior quebrou em uma semana.",
    title: "Base Suporte Para PC Notebook Alumínio Portátil Articulado Dobrável Tablet Laptop Mesa Hytalux Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_719010-MLA110559363083_042026-V.webp",
    price: 24.15,
    originalPrice: 32.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0H3788T72?tag=dmagno04-20", price: 18.9 },
    ],
  },
  {
    slug: "teclado-ergonomico-sem-fio-logitech-wave-keys-graf",
    url: "https://meli.la/2UAfr3i",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    featured: true,
    review: "Comprei por dois motivos: precisava alternar rápido entre o notebook Windows e o MacBook, e a ergonomia ajuda muito nas horas que passo no computador — ficou bem mais confortável digitar.",
    title: "Teclado Ergonômico Sem Fio Logitech Wave Keys - Grafite Inglês US",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_739716-MLA99453694320_112025-V.webp",
    price: 459,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0CHB9PD4M?tag=dmagno04-20", price: 409.9 },
    ],
  },
  {
    slug: "cabo-thunderbolt-3-ugreen-usb-c-para-hdmi-4k-refor",
    url: "https://meli.la/24JFJL6",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Todo cabo que compro é Ugreen — qualidade que dispensa comentários, sempre cumprem o que prometem.",
    title: "Cabo Thunderbolt 3 Ugreen USB-C Para HDMI 4K Reforçado - Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_852747-MLA99395901500_112025-V.webp",
    price: 124.42,
    originalPrice: 299,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07G5691LJ?tag=dmagno04-20", price: 107.9 },
    ],
  },
  {
    slug: "mousepad-extra-grande-caramelo-90x40cm-deskpad-cou",
    url: "https://meli.la/2DDJo5k",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    review: "Uma das melhores aquisições que fiz — muito bonito, dá um charme ao escritório e ainda deixa o mouse livre pra correr sem limites.",
    title: "Mousepad Extra Grande Caramelo 90x40cm Deskpad Couro Antiderrapante Mesa - Kingpad",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_701855-MLA102404626214_122025-V.webp",
    price: 47.49,
    originalPrice: 49.99,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B09HSQBYY1?tag=dmagno04-20", price: 51.14 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/5VUP7JpZjr", price: 37.9, note: "cor caramelo" },
    ],
  },
  {
    slug: "flanela-pano-protecao-tela-e-teclado-apple-macbook",
    url: "https://meli.la/2pRQRVh",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Protege a tela da gordura que fica no teclado e passa pro display quando fecho o MacBook — mantém tudo limpo por mais tempo. Não é qualquer pano que serve pra isso, e esse é o ideal.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\" — era outro item completamente diferente. Reverificado 2x, estável.",
    title: "Flanela Pano Proteção Tela E Teclado Apple Macbook 13 A 16",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_612151-MLB92259649659_092025-V-flanela-pano-proteco-tela-e-teclado-apple-macbook-13-a-16.webp",
    price: 63.79,
    originalPrice: 78.28,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0D9WPRCH8?tag=dmagno04-20", price: 79.97 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/3B6UJFhIOw", price: 32.0 },
    ],
  },
  {
    slug: "fone-bluetooth-wave-buds-2-tws-azul",
    url: "https://meli.la/2QtskjE",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Fone bom, grave gostoso, o filtro de ruído funciona muito bem — e poder controlar quanto do ambiente eu quero ouvir foi uma baita sacada.",
    title: "Fone Bluetooth Wave Buds 2 TWS Azul",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_811984-MLA99445406304_112025-V.webp",
    price: 234.5,
    originalPrice: 369,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DKJKTPWJ?tag=dmagno04-20", price: 219 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/30n46whvjv", price: 297.0, note: "cor azul" },
    ],
  },
  {
    slug: "headset-sem-fio-logitech-zone-vibe-100-grafite",
    url: "https://meli.la/2pC6977",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Estava sofrendo com dores de cabeça pelos fones antigos e precisava de algo leve e confortável sem abrir mão da qualidade de áudio pro trabalho — esse foi o único que bateu tudo isso nas minhas pesquisas.",
    title: "Headset Sem Fio Logitech Zone Vibe 100 - Grafite",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_866279-MLA99513179228_112025-V.webp",
    price: 594.15,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0B8C31YXR?tag=dmagno04-20", price: 529.99 },
    ],
  },
  {
    slug: "capa-para-macbook-air-13-m4-m3-m2-protetor-teclado",
    url: "https://meli.la/2hrMDnX",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Gosto de cuidar bem do que tenho, e esse kit ajuda exatamente nisso — protege o equipamento por completo.",
    title: "Capa Para Macbook Air 13 M4/M3/M2 Protetor Teclado + Bag Transparente Cristal",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_971777-MLA95522187642_102025-V.webp",
    price: 117.23,
    originalPrice: 169.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0FC2JFQ2K?tag=dmagno04-20", price: 88 },
    ],
  },
  {
    slug: "jogo-limpa-telas-pc-notebook-120ml-pano-microfibra",
    url: "https://meli.la/2qBZeEU",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Simples, mas muito funcional — não fico sem.",
    title: "Jogo Limpa Telas PC Notebook 120ml + Pano Microfibra Start",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_727350-MLA100087934009_122025-V.webp",
    price: 22.2,
    originalPrice: 28.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0D5BXC1JL?tag=dmagno04-20", price: 25.78 },
    ],
  },
  {
    slug: "cabo-ugreen-quick-charge-4-0-usb-c-1m-blindado-cin",
    url: "https://meli.la/1nDCC7b",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Todo cabo que compro é Ugreen — qualidade que dispensa comentários, sempre cumprem o que prometem.",
    title: "Cabo Ugreen Quick Charge 4.0 USB-C 1m Blindado - Cinza",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_705800-MLA99599259526_122025-V.webp",
    price: 36.56,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07PP2QHZD?tag=dmagno04-20", price: 48.9 },
    ],
  },
  {
    slug: "ugreen-organizador-cabo-2-metros-40354",
    url: "https://meli.la/1fjWsJZ",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Solução prática pra manter os cabos enrolados e organizados.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Ugreen - Organizador Cabo 2 Metros - 40354 Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_626476-MLB92317605521_092025-V.webp",
    price: 24.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07ZC346SK?tag=dmagno04-20", price: 27.69 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/3VjKhrg1j2", price: 23.9 },
    ],
  },
  {
    slug: "mouse-sem-fio-logitech-mx-vertical-ergonomico-cinz",
    url: "https://meli.la/1iZ7b9D",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Sentia dores constantes no punho, e esse mouse resolveu — hoje não fico mais sem ele.",
    title: "Mouse Sem Fio Logitech MX Vertical Ergonômico Cinza",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_926785-MLA99858509739_112025-V.webp",
    price: 533.22,
    originalPrice: 579.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B07PNKGKBX?tag=dmagno04-20", price: 479.9 },
    ],
  },
  {
    slug: "teclado-sem-fio-signature-k650-grafite-logitech-ci",
    url: "https://meli.la/1Fe9x1H",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Segundo teclado do nosso setup, usado pela minha esposa — muito bom e confortável.",
    title: "Teclado Sem Fio Signature K650 Grafite Logitech Cinza-Escuro",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_780490-MLA99929764499_112025-V.webp",
    price: 241.3,
    originalPrice: 289.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0BK9YLKPM?tag=dmagno04-20", price: 239.18 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/1gHgWViL9j", price: 325.0, note: "cor preta" },
    ],
  },
  {
    slug: "copo-termico-inox-cafe-cha-antivazamento-vacuum",
    url: "https://meli.la/1FStUzP",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    review: "Ajuda muito com o cafezinho — mantém a temperatura ideal e, com a tampa lacrada, não derrama em volta.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Copo Térmico Inox Café Chá Anti-vazamento Vacuum 510ml Azul Coffee",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_642290-MLB113406160621_062026-V.webp",
    price: 27.06,
    originalPrice: 69.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0FFBN14CB?tag=dmagno04-20", price: 49.9 },
    ],
  },
  {
    slug: "kit-limpa-telas-tablet-celular-notebook-computadore",
    url: "https://meli.la/21KQWD3",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Simples, mas muito funcional — não fico sem.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Kit Limpa Telas Tablet Celular Notebook Computadores Vidros",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_806895-MLB73331229509_122023-V.webp",
    price: 30.99,
    originalPrice: 32.99,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DQL9YDG3?tag=dmagno04-20", price: 15.9 },
    ],
  },
  {
    slug: "cinto-de-fitness-com-alavanca-lever-buckle",
    url: "https://meli.la/2bjvGGT",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Essencial pra quem treina perna com carga alta — uso sempre nesses dias.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: método antigo lia texto/imagem soltos que NÃO batiam com o destino real do botão \"Ir para produto\" (bug sério — o Danilo clicou e caiu em produto totalmente diferente). Dado extraído agora do mesmo container do botão, garantindo consistência.",
    title: "Cinturão De Musculação Rudel Rdl2-151 Pride Red",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_898954-MLB78818567107_082024-V-cinturo-de-musculaco-rudel-rdl2-151-pride-red.webp",
    price: 144.65,
    originalPrice: 153.26,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/8fRQrNHgx6", price: 147.6 },
    ],
  },
  {
    slug: "straps-fitness-rudel-h-8-204-preto",
    url: "https://s.shopee.com.br/8pkr3gH3c9",
    platform: "SHOPEE",
    categories: ["Fitness"],
    review: "Uso com menos frequência, mas é muito bom — ajuda bastante, só não pode virar muleta.",
    verifiedAt: "2026-09-18",
    verificationNote: "ANÚNCIO DO ML MORREU (2026-09-18): meli.la/2Y5nFAX passou a cair na página de listas do perfil, sem botão \"Ir para produto\". Promovido para a Shopee, que já era oferta cadastrada e segue viva (HTTP 200) pelo mesmo preço de R$ 35,89 — mesmo produto, então o review continua válido. Substituto no ML já mapeado em `retiredLinks` para quando der: Strap Rudel H8 (MLB4687812325) por R$ 25. Slug mantido para preservar histórico de cliques.",
    title: "Straps Fitness Rudel H-8 204 Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_769827-MLB95776743023_102025-V.webp",
    price: 35.89,
  },
  {
    slug: "protetor-de-punho-profissional-crossfit-munhequeir",
    url: "https://meli.la/1Frc4Wu",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Depois de problemas com tendinite, esse protetor me dá segurança e ajuda a evitar lesão.",
    title: "Protetor De Punho Profissional Crossfit Munhequeira Pulso - Rosa",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_721892-MLA99598079074_122025-V.webp",
    price: 33,
    originalPrice: 45.54,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DRMPZ27W?tag=dmagno04-20", price: 40.45 },
    ],
  },
  {
    slug: "kit-3-regata-masculina-americano-canelada-algodao",
    url: "https://meli.la/2iHrnTX",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário", "Fitness"],
    review: "Muito boa — uso todos os dias pra treinar, já estou comprando mais.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (verificação anterior usava alt-text solto, que pegou produto errado). Confirmado 2x, estável.",
    title: "Kit 3 Regata Masculina Americano Canelada Algodão Premium",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_856120-MLB109278068437_032026-V-kit-3-regata-masculina-americano-canelada-algodo-premium.webp",
    price: 59.3,
    originalPrice: 70,
  },
  {
    slug: "cinta-masculina-modeladora-abdominal-ajustavel-ema",
    url: "https://meli.la/233NUCw",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Uso na maioria dos treinos — dá conforto e segurança.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: a página de recomendação do ML troca o produto em destaque até sem reload (algoritmo ativo, não é só cache). A versão anterior (\"Preto GG\") vinha com imagem colagem/promocional que não batia visualmente com o produto. Essa variante \"Lomba Cinza G\" tem foto limpa e bate com o tipo de produto (cinta abdominal).",
    title: "Cinta Modeladora Masculina Abdominal Dupla Compressão Lomba Cinza G",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_801197-MLB108656655278_032026-V.webp",
    price: 86.33,
    originalPrice: 129.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GSHJYPCZ?tag=dmagno04-20", price: 109 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/50Y8WOrTkm", price: 78.65 },
    ],
  },
  {
    slug: "calca-tactel-masculino-jogger-com-elastano-academi",
    url: "https://meli.la/2gr6yyi",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness", "Vestuário"],
    featured: true,
    review: "Me impressionei com a compra — uso quase todo dia, comprei três e hoje só treino com elas.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (verificação anterior pegou variante errada). Confirmado 2x, estável.",
    title: "Calça Tactel Masculino Jogger C/ Elastano Academia Treino",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_692315-MLB87398103458_072025-V-calca-tactel-masculino-jogger-c-elastano-academia-treino.webp",
    price: 36.17,
    originalPrice: 69,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GSCM9KSG?tag=dmagno04-20", price: 35.91 },
    ],
  },
  {
    slug: "munhequeira-musculacao-crossfit-lpo-elastica-alta",
    url: "https://meli.la/1KE8Dgv",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Depois de problemas com tendinite, essa munhequeira me dá segurança e ajuda a evitar lesão.",
    title: "Munhequeira Musculação Crossfit LPO Elástica Alta Compressão - Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_825097-MLA105750783064_022026-V.webp",
    price: 34.44,
    originalPrice: 39.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0CV18Q36K?tag=dmagno04-20", price: 42.9 },
    ],
  },
  {
    slug: "shorts-2-em-1-termico-de-compressao-com-bolso-secr",
    url: "https://meli.la/1skhdLd",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Muito bom — resolve o problema de assaduras e mantém tudo discreto durante o treino.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (verificação anterior pegou variante desincronizada do destino real do link). Confirmado 2x, estável.",
    title: "Shorts 2 Em 1 Térmico De Compressão Bolso Secreto Academia",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_710628-MLB110967764522_052026-V-shorts-2-em-1-termico-de-compresso-bolso-secreto-academia.webp",
    price: 27.77,
    originalPrice: 54.9,
  },
  {
    slug: "relogio-casio-unissex-vintage-aq-230a-1dmq-pratead",
    url: "https://meli.la/2RaFbfu",
    platform: "MERCADO_LIVRE",
    categories: ["Acessórios"],
    review: "Muito bom e elegante.",
    title: "Relógio Casio Unissex Vintage AQ-230A-1DMQ Prateado",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_638064-MLA99489095824_112025-V.webp",
    price: 204.05,
    originalPrice: 454.36,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/904HFzGQHC", price: 250.04 },
    ],
  },
  {
    slug: "kit-3-regata-oversized-machao-streetwear-lisa-casu",
    url: "https://meli.la/12feN5K",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário", "Fitness"],
    featured: true,
    review: "Muito boa — uso sempre por baixo da roupa, como primeira pele.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: reverificado com método do container do botão \"Ir para produto\" (mesmo vendedor D2G, imagem/título levemente diferentes do que estava salvo). Confirmado 2x, estável.",
    title: "Kit 3 Regata Oversized Machão Streetwear Lisa Casual Básicas",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_839421-MLB104333596016_012026-V-kit-3-regata-oversized-macho-streetwear-lisa-casual-basicas.webp",
    price: 76.03,
    originalPrice: 143.45,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DHLX9Y9F?tag=dmagno04-20", price: 129.9 },
    ],
  },
  {
    slug: "regata-oversized-masculino-tamanho-grande-basica-l",
    url: "https://meli.la/2bUEgJW",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário", "Fitness"],
    review: "Regata básica que uso bastante no dia a dia, confortável e sem frescura.",
    title: "Regata Oversized Masculino Tamanho Grande Básica Lisa - Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_944768-MLB94446815565_102025-V.webp",
    price: 27,
    originalPrice: 64.14,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0FPNN2PCS?tag=dmagno04-20", price: 56.9 },
    ],
  },
  {
    slug: "suplemento-em-po-panic-150g-adaptogen-uva-com-crea",
    url: "https://meli.la/1USEMLc",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Um dos melhores que já tomei.",
    title: "Suplemento em Pó Panic 150g Adaptogen Uva com Creatina",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_861264-MLA100080909647_122025-V.webp",
    price: 38.8,
    originalPrice: 66,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0B2J5KQB7?tag=dmagno04-20", price: 50 },
    ],
  },
  {
    slug: "pedalboard-luxo-detalhe-em-madeira-universal-com-v",
    url: "https://meli.la/2vup3ow",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Compacto — uso com minha HX e o footswitch, cumpre bem o papel.",
    title: "Pedalboard Luxo Detalhe em Madeira Universal com Velcro Fuhrmann PB5",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_800509-MLA100008009715_122025-V.webp",
    price: 137.75,
    originalPrice: 259.63,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/9ANhSIFmwF", price: 145.0 },
    ],
  },
  {
    slug: "footswitch-cabo-50cm-hxstomp-ampero-nux-loop-core",
    url: "https://meli.la/2pDX1qr",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Muito bom, facilitou o uso da HX no meu setup.",
    title: "Footswitch Cabo 50cm HXStomp Ampero NUX Loop Core Vamp FS2NL",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_949576-MLA105895323032_022026-V.webp",
    price: 209,
  },
  {
    slug: "adaptador-p10-macho-p2-femea-estereo-daddario-pwp0",
    url: "https://meli.la/2nADtNJ",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Um dos melhores do mercado — vale investir na durabilidade e qualidade.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/SKU/imagem antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Adaptador P10 Macho P2 Fêmea Estéreo D'Addario PW-P047E",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_895564-MLB84762878925_052025-V.webp",
    price: 123.18,
    originalPrice: 126.99,
  },
  {
    slug: "fita-gaffer-tape-opcao-cores-12mm-x-5mts-fluoresce",
    url: "https://meli.la/23tv7hh",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    review: "Gosto de sinalizar tudo com meus dados, e essa fita é a solução perfeita.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Fita Gaffer Tape Opção Cores 12mm X 5mts Fluorescente Neon",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_817424-MLB93932215678_102025-V-fita-gaffer-tape-opcao-cores-12mm-x-5mts-fluorescente-neon.webp",
    price: 23.45,
    originalPrice: 25.22,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0DWB9Y591?tag=dmagno04-20", price: 86.97 },
    ],
  },
  {
    slug: "mesa-dobravel-portatil-palisad-aluminio-branco-90x",
    url: "https://meli.la/1k5kKFp",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    review: "Ótima sacada — super prática, dá pra levar pra qualquer lugar.",
    title: "Mesa Dobrável Portátil Palisad Alumínio Branco 90x60x70cm",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_879613-MLA96146063437_102025-V.webp",
    price: 119.2,
    originalPrice: 149,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0777QNWGL?tag=dmagno04-20", price: 159.9 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/5ArYihqqPp", price: 138.8, note: "90x60 cm" },
    ],
  },
  {
    slug: "bolsa-bag-mochila-reforcada-alca-para-pedalboard-f",
    url: "https://meli.la/1Sa2yEP",
    platform: "MERCADO_LIVRE",
    categories: ["Música"],
    review: "Muito boa — protege e facilita o transporte do pedalboard.",
    verifiedAt: "2026-07-13",
    verificationNote: "CORRIGIDO 2026-07-13: produto/imagem/slug antigos não batiam com o destino real do botão \"Ir para produto\". Reverificado 2x, estável.",
    title: "Bolsa Bag Mochila Reforçada Alça Para Pedalboard Fuhrmann Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_878806-MLB92394662567_092025-V.webp",
    price: 253,
    originalPrice: 302.5,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/8KoaSm55Aq", price: 189.0 },
    ],
  },
  {
    slug: "colete-corretor-postural-cervical-alinha-postura",
    url: "https://meli.la/1ALbTSX",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Colete Corretor Postural Para Coluna Cervical Alinha Postura",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_749929-MLB101159772275_122025-V.webp",
    price: 33.7,
    originalPrice: 47.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0F74P6KNR?tag=dmagno04-20", price: 42.99 },
    ],
  },
  {
    slug: "kit-6-regata-americano-canelada-premium-masculina",
    url: "https://meli.la/2XntxKN",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário", "Fitness"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Kit 6 Regata Modelo Americano Canelada Premium Masculina",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_774032-MLB109630771191_032026-V-kit-6-regata-modelo-americano-canelada-premium-masculina.webp",
    price: 117,
    originalPrice: 236.18,
  },
  {
    slug: "kit-apoio-de-copo-4-porta-copos-bambu",
    url: "https://meli.la/2GRtf2r",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Kit Apoio De Copo 4 Porta Copos Bambu Quadrado Redondo",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_951678-MLB114714260747_072026-V.webp",
    price: 27.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GSCVQLCV?tag=dmagno04-20", price: 26.89 },
    ],
  },
  {
    slug: "porta-retrato-duplo-10x15-madeira-decoracao-moldura-foto",
    url: "https://meli.la/2ijTHAV",
    platform: "MERCADO_LIVRE",
    categories: ["Casa"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Porta Retrato Duplo 10x15 Madeira Decoração Moldura Foto Marrom",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_607838-MLB92880090739_092025-V.webp",
    price: 35.23,
    originalPrice: 55.91,
  },
  {
    slug: "suporte-para-celular-mesa-organizador",
    url: "https://meli.la/1Y6Fwvf",
    platform: "MERCADO_LIVRE",
    categories: ["Setup"],
    verifiedAt: "2026-07-22",
    verificationNote: "Verificado 2026-07-22 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Suporte Para Celular Mesa Com Organizador",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_761700-MLB93148237428_092025-V.webp",
    price: 79,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B0GRBYNWM3?tag=dmagno04-20", price: 32.9 },
    ],
  },
  {
    slug: "kit-2-regata-masculina-verao-canelada-americana-slim",
    url: "https://meli.la/14vwa77",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário", "Fitness"],
    verifiedAt: "2026-07-23",
    verificationNote: "Verificado 2026-07-23 com o método do container do botão \"Ir para produto\" — confirmado 2x, estável.",
    title: "Kit 2 Regata Masculina Verão Treino Canelada Americana Slim",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_736445-MLB105233260645_012026-V-kit-2-regata-masculina-vero-treino-canelada-americana-slim.webp",
    price: 43.9,
    originalPrice: 78,
  },
  {
    slug: "kit-3-camiseta-regatas-masculinas-cavada-treino-musculacao",
    url: "https://meli.la/2QgHLEc",
    platform: "MERCADO_LIVRE",
    categories: ["Vestuário", "Fitness"],
    featured: true,
    review: "Essa é a que eu uso pra treino pesado — bem cavada, libera o ombro e não incomoda em nenhum movimento.",
    verifiedAt: "2026-08-09",
    verificationNote: "ATUALIZADO 2026-08-09: voltou para meli.la/2QgHLEc (o link original, do mesmo vendedor Éved) a pedido do Danilo. Verificado 2x pelo método do container do botão \"Ir para produto\" — destino MLB-3240197154, título/imagem batendo, estável. Preço caiu de R$ 76,22 para R$ 70,66 (29% OFF sobre R$ 99,80). Slug mantido pra não quebrar links /r/ já compartilhados.",
    title: "Kit 3 Camiseta Regatas Masculinas Cavada Treino Musculação",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_622500-MLB86947060374_072025-V-kit-3-camiseta-regatas-masculinas-cavada-treino-musculaco.webp",
    price: 70.66,
    originalPrice: 99.8,
  },
  {
    slug: "kit-2-joelheiras-compressao-neoprene-esportiva",
    url: "https://meli.la/2mVE4kV",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto (o card do hub mostrava valor errado).",
    title: "Kit 2 Joelheiras Compressão Neoprene Esportiva Preto Verde",
    image: "https://http2.mlstatic.com/D_NQ_NP_772398-MLA106496060919_022026-O.webp",
    price: 21.6,
    originalPrice: 49.9,
  },
  {
    slug: "creatina-monohidratada-pura-500g-dark-lab",
    url: "https://meli.la/2AGuJAs",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto (o card do hub mostrava valor errado).",
    title: "Creatina Monohidratada Pura 500g Dark Lab",
    image: "https://http2.mlstatic.com/D_NQ_NP_942122-MLA99923169249_112025-O.webp",
    price: 44.9,
    originalPrice: 129.9,
  },
  {
    slug: "coqueteleira-shaker-academia-700ml-dark-lab",
    url: "https://meli.la/32XBveB",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto (o card do hub mostrava valor errado).",
    title: "Coqueteleira Shaker Academia 700ml Dark Lab",
    image: "https://http2.mlstatic.com/D_NQ_NP_784857-MLA99625616614_122025-O.webp",
    price: 19,
    originalPrice: 29.9,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/8V80f54Rpt", price: 19.9 },
    ],
  },
  {
    slug: "luva-academia-musculacao-max-grip-anti-calo",
    url: "https://meli.la/32HVkCY",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto (o card do hub mostrava valor errado).",
    title: "Luva Academia Musculação Treino Max Grip Protetor Anti Calo",
    image: "https://http2.mlstatic.com/D_NQ_NP_617838-MLB87260387792_072025-O-luva-academia-musculacao-treino-max-grip-protetor-anti-calo.webp",
    price: 19.11,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/80Bk4A6Lqo", price: 6.9 },
    ],
  },
  {
    slug: "kit-5-faixa-elastica-mini-band-extensor",
    url: "https://meli.la/28d3Nmg",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto (o card do hub mostrava valor errado).",
    title: "Kit 5 Faixa Elástica Super Mini Band Extensor Para Treino",
    image: "https://http2.mlstatic.com/D_NQ_NP_982791-MLA110468747005_042026-O.webp",
    price: 19.99,
  },
  {
    slug: "pasta-de-amendoim-dr-peanut-gourmet-chocotine-600g",
    url: "https://meli.la/1XsTi9D",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto (o card do hub mostrava valor errado).",
    title: "Pasta De Amendoim Dr. Peanut Gourmet Sabor Chocotine 600g",
    image: "https://http2.mlstatic.com/D_NQ_NP_909125-MLA112365319432_062026-O.webp",
    price: 39.59,
    originalPrice: 62.5,
  },
  {
    slug: "whey-protein-concentrado-1kg-growth-chocolate",
    url: "https://meli.la/2X57Qd8",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Whey que eu tomo no dia a dia — Growth é custo-benefício honesto, sem enrolação de marketing.",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Whey Protein Concentrado 1kg Growth Supplements - Chocolate",
    image: "https://http2.mlstatic.com/D_NQ_NP_810392-MLA98296434364_112025-O.webp",
    price: 199.72,
  },
  {
    slug: "creatina-monohidratada-250g-growth",
    url: "https://meli.la/2FgSoAQ",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    review: "Minha creatina do dia a dia. Monohidratada pura, que é a que tem evidência — tomo todo dia, treino ou não.",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Creatina Monohidratada 250g Growth Supplements - Sem Sabor",
    image: "https://http2.mlstatic.com/D_NQ_NP_662415-MLA97812910758_112025-O.webp",
    price: 39.9,
  },
  {
    slug: "l-glutamina-250g-growth",
    url: "https://meli.la/1tJ9sKH",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "L-Glutamina 250g Growth Supplements - Sem Sabor",
    image: "https://http2.mlstatic.com/D_NQ_NP_728651-MLA106461309532_022026-O.webp",
    price: 62.9,
  },
  {
    slug: "bcaa-2-1-1-120-capsulas-growth",
    url: "https://meli.la/1EFsB9i",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "BCAA 2:1:1 120 cápsulas Growth Supplements",
    image: "https://http2.mlstatic.com/D_NQ_NP_608974-MLA106384716530_022026-O.webp",
    price: 27.06,
  },
  {
    slug: "pre-treino-haze-hardcore-300g-growth-uva",
    url: "https://meli.la/24LT5XP",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Pré-treino Haze Hardcore 300g Growth Supplements - Uva",
    image: "https://http2.mlstatic.com/D_NQ_NP_947028-MLA98776405883_112025-O.webp",
    price: 99.9,
  },
  {
    slug: "omega-3-oleo-de-peixe-75-caps-growth",
    url: "https://meli.la/273Q1FZ",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Omega 3 Óleo De Peixe 75 Softgel Growth Supplements",
    image: "https://http2.mlstatic.com/D_NQ_NP_962239-MLA103882656131_012026-O.webp",
    price: 34.9,
  },
  {
    slug: "multivitaminico-120-caps-growth",
    url: "https://meli.la/31ufZA4",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Multivitamínico 120 Cáps. Growth Supplements - Sabor Neutro",
    image: "https://http2.mlstatic.com/D_NQ_NP_723031-MLA98380453196_112025-O.webp",
    price: 49.9,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/8AVAGT5iVr", price: 79.69 },
    ],
  },
  {
    slug: "hiper-mass-1kg-growth-chocolate",
    url: "https://meli.la/2PsKJxZ",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Hiper Mass 1kg Growth Supplements - Sabor Chocolate",
    image: "https://http2.mlstatic.com/D_NQ_NP_713346-MLA107082143625_022026-O.webp",
    price: 57.9,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/7fYtfY7cWm", price: 79.9 },
    ],
  },
  {
    slug: "barra-de-proteina-cx-12-growth-cookies",
    url: "https://meli.la/18JtFtW",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Barra De Proteína (cx. 12) Growth Supplements - Cookies & Cream",
    image: "https://http2.mlstatic.com/D_NQ_NP_946650-MLA106391745924_022026-O.webp",
    price: 58.1,
  },
  {
    slug: "proteina-isolada-de-soja-growth-chocolate-1kg",
    url: "https://meli.la/2DNpL47",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Proteína Isolada de Soja Growth Supplements Chocolate 1kg",
    image: "https://http2.mlstatic.com/D_NQ_NP_751538-MLA111483935046_052026-O.webp",
    price: 94.9,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/2LXNJlNG2v", price: 149.9 },
    ],
  },
  {
    slug: "power-arginine-120-caps-growth",
    url: "https://meli.la/1GYTTaA",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Power Arginine 120 Cáps. (600mg) Growth Supplements",
    image: "https://http2.mlstatic.com/D_NQ_NP_638877-MLA107020964799_022026-O.webp",
    price: 38.7,
  },
  {
    slug: "coenzima-q10-100mg-60-caps-growth",
    url: "https://meli.la/1N1iJhH",
    platform: "MERCADO_LIVRE",
    categories: ["Fitness"],
    kind: "lista",
    verifiedAt: "2026-07-24",
    verificationNote: "Verificado 2026-07-24: link de afiliado gerado no Gerador de Links do ML (etiqueta dlmagnosoliveira) e conferido pelo método do container do botão \"Ir para produto\" — destino, título e imagem batem. Preço confirmado na página real do produto.",
    title: "Coenzima Q10 (100mg 60 Caps) Growth Supplements",
    image: "https://http2.mlstatic.com/D_NQ_NP_603983-MLA111195441771_052026-O.webp",
    price: 59.9,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/2BDx7SNtNu", price: 59.9 },
    ],
  },
  {
    slug: "microfone-hollyland-lark-m2s-duo-usb-c-2-pessoas",
    url: "https://meli.la/26sGXNK",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    review: "Resolveu meu maior problema de gravação: som limpo longe da câmera, sem cabo e sem depender do microfone do celular.",
    verifiedAt: "2026-07-31",
    verificationNote: "Verificado 2026-07-31 com o método do container do botão \"Ir para produto\" — destino MLB45445679, título/preço/imagem batendo, confirmado 2x estável. Sem oferta Amazon de propósito: lá só existe o M2S de 1 transmissor (B0DNQ8CLXR) e o M2 Duo (modelo anterior) — nenhum é o M2S Duo deste anúncio.",
    title: "Microfone Hollyland Lark M2s Duo USB-C Duplo P/ 2 Pessoas - Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_982902-MLA99561736536_122025-V.webp",
    price: 772.9,
    originalPrice: 1310,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/20uWv9OWit", price: 739.99 },
    ],
  },
  {
    slug: "teclado-sem-fio-logitech-ergo-k860-layout-dividido",
    url: "https://meli.la/2F92oEd",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    kind: "lista",
    featured: true,
    review: "Quero esse pro escritório — passo o dia digitando e o layout dividido é o que promete resolver o pulso.",
    verifiedAt: "2026-08-25",
    verificationNote: "Reverificado 2026-08-25 pelo método do container do botão \"Ir para produto\" — destino MLB16593313 estável, imagem batendo. PREÇO SUBIU nos dois lados: ML de R$ 682,24 para R$ 754 (de R$ 859,90, 12% OFF) e Amazon de R$ 609,90 para R$ 701,10 (só 6 em estoque). A Amazon segue R$ 52,90 mais barata. Promovido a destaque a pedido do Danilo: por ser da prateleira \"Na minha lista\", vira o primeiro destaque de lá e não engorda o topo da prateleira \"Eu uso\".",
    title: "Teclado Sem Fio Logitech Ergo K860 Com Layout Dividido Preto — Inglês US Qwerty",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_622563-MLA99529535854_122025-V.webp",
    price: 754,
    originalPrice: 859.9,
    offers: [
      { platform: "AMAZON", url: "https://www.amazon.com.br/dp/B08ZRC6LP4?tag=dmagno04-20", price: 701.1 },
      { platform: "SHOPEE", url: "https://s.shopee.com.br/4fvI7mskQk", price: 1247.17 },
    ],
  },
  {
    slug: "microfone-lark-a1-hollyland-mini-usb-c-preto",
    url: "https://meli.la/2xMEsnb",
    platform: "MERCADO_LIVRE",
    categories: ["Tech"],
    kind: "lista",
    verifiedAt: "2026-08-04",
    verificationNote: "Verificado 2026-08-04 com o método do container do botão \"Ir para produto\" — destino MLB51857731, título/preço/imagem batendo, confirmado 2x estável. Entra como indicação: é a versão mini/1 transmissor do mesmo fabricante do Lark M2s Duo que o Danilo usa, então ele indica sem ter este modelo.",
    title: "Microfone Lark A1 Hollyland Mini USB-C — Preto",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_836376-MLA99418800236_112025-V.webp",
    price: 315,
    offers: [
      { platform: "SHOPEE", url: "https://s.shopee.com.br/3B6UJIK5M8", price: 339.0 },
    ],
  },
  {
    slug: "esponja-banho-esfoliante-corporal-cordao-massagem",
    url: "https://s.shopee.com.br/6L3W3G6DzP",
    platform: "SHOPEE",
    categories: ["Casa"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado).",
    title: "Esponja Banho Esfoliante Pele 67.5x8x0.5cm Esponja Corporal Cordão Massagem Ferramenta Para Esfregar",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-ltcjl154uwakd9",
    price: 14.99,
    originalPrice: 23.99,
  },
  {
    slug: "capa-vidro-fosco-ag-glass-premium-iphone",
    url: "https://s.shopee.com.br/5q7FSL880M",
    platform: "SHOPEE",
    categories: ["Tech"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado).",
    title: "Capa de Vidro Fosco AG Glass Premium Para iPhone 13/14/15/16/17",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjjwg9gidvra63",
    price: 23.99,
  },
  {
    slug: "cotoveleira-compressao-ajustavel-esporte-mbfit",
    url: "https://s.shopee.com.br/50Y8SirBU5",
    platform: "SHOPEE",
    categories: ["Fitness"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado). TÍTULO NEUTRALIZADO a pedido do Danilo: o anúncio original traz condição médica no título (SEO do vendedor). Produto, imagem, preço e link de destino são exatamente os do anúncio — só o texto exibido foi reescrito de forma neutra.",
    title: "Cotoveleira de Compressão Ajustável para Esporte Mbfit",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7ra0o-m4z45i1taxge79",
    price: 17.99,
  },
  {
    slug: "shorts-bermuda-compressao-masculina-corrida-treino",
    url: "https://s.shopee.com.br/4qEiGProp4",
    platform: "SHOPEE",
    categories: ["Fitness", "Vestuário"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado).",
    title: "Shorts Masculino Bermuda Compressão Para Corrida Treino",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdbatuwr0lc1e5",
    price: 22.96,
    originalPrice: 59.99,
  },
  {
    slug: "kit-10-topper-pedal-guitarra-botao-pedaleira",
    url: "https://s.shopee.com.br/6L3W3JR0mb",
    platform: "SHOPEE",
    categories: ["Música"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado).",
    title: "Kit 10 Topper Para Pedal de Guitarra — Botão de Pedaleira",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m4105ai4csht27",
    price: 29.98,
  },
  {
    slug: "cinta-colete-redutora-masculina-camisa-modeladora",
    url: "https://s.shopee.com.br/5VUP3j9OgG",
    platform: "SHOPEE",
    categories: ["Fitness"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado). TÍTULO NEUTRALIZADO a pedido do Danilo: o anúncio original traz condição médica no título (SEO do vendedor). Produto, imagem, preço e link de destino são exatamente os do anúncio — só o texto exibido foi reescrito de forma neutra.",
    title: "Cinta Colete Redutora Masculina Camisa Modeladora Slim Fit Postural",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-825zs-mjspwookzvur9f",
    price: 35.99,
  },
  {
    slug: "colete-modelador-masculino-compressivo-opta-corpus",
    url: "https://s.shopee.com.br/4fvI46sSA3",
    platform: "SHOPEE",
    categories: ["Fitness"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado). TÍTULO NEUTRALIZADO a pedido do Danilo: o anúncio original traz condição médica no título (SEO do vendedor). Produto, imagem, preço e link de destino são exatamente os do anúncio — só o texto exibido foi reescrito de forma neutra.",
    title: "Colete Modelador Masculino Compressivo Opta Corpus",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m7tbpp9e2ateee",
    price: 157.68,
    originalPrice: 219,
  },
  {
    slug: "colete-corretor-postural-unissex-mb-fit",
    url: "https://s.shopee.com.br/5LAyrQA21F",
    platform: "SHOPEE",
    categories: ["Fitness"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado). Conferido contra o colete postural do ML já no catálogo: são produtos diferentes (o do ML é tira em 8 sobre os ombros; este é órtese com painel traseiro e ímãs) — por isso entrou como item novo, não como oferta.",
    title: "Colete Corretor Postural Unissex Preto MB Fit",
    image: "https://down-br.img.susercontent.com/file/c36285edf751a52b7db8f9d9c5da0539",
    price: 46,
  },
  {
    slug: "kit-2-cintas-modeladoras-masculinas-bodyshaper",
    url: "https://s.shopee.com.br/5fnpG28lLL",
    platform: "SHOPEE",
    categories: ["Fitness"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado). Conferido contra a cinta abdominal do ML já no catálogo: são produtos diferentes (a do ML é cinta de cintura; esta é camiseta modeladora de torso inteiro) — por isso entrou como item novo, não como oferta.",
    title: "Kit 2 Cintas Modeladoras Masculinas Bodyshaper Corretor Postural",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lwsln2ldhl7629",
    price: 64.9,
    originalPrice: 99.9,
  },
  {
    slug: "kit-3-cintas-modeladoras-postural-masculina-bodys",
    url: "https://s.shopee.com.br/40fbGsuzVr",
    platform: "SHOPEE",
    categories: ["Fitness"],
    verifiedAt: "2026-08-09",
    verificationNote: "Verificado 2026-08-09 pela API oficial de produto da Shopee (get_pc) usando o item_id/shop_id exatos do pedido do Danilo — título, imagem e preço vêm do mesmo anúncio que ele comprou, sem ambiguidade de card de recomendação. Link de afiliado gerado no painel oficial (Link personalizado). Conferido contra a cinta abdominal do ML já no catálogo: são produtos diferentes (a do ML é cinta de cintura; esta é camiseta modeladora de torso inteiro) — por isso entrou como item novo, não como oferta.",
    title: "Kit 3 Cintas Modeladoras Postural Masculina Compressão Bodyshaper",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lofhzs3r9b2faa",
    price: 91.9,
    originalPrice: 149.9,
  },

  /*
   * KITS GROWTH — grupo próprio criado 2026-08-25 a pedido do Danilo, a partir
   * da vitrine "Kits" da loja oficial Growth no ML. São 36 anúncios: poucas
   * composições (whey+creatina, whey+multivitamínico+creatina, whey+creapure,
   * linha Basic) em muitos sabores. Entram como "lista" porque ele usa whey e
   * creatina Growth avulsos, não os kits — então indica, não afirma que usa.
   * Preços lidos de .poly-price__amount (atual) e .andes-money-amount--previous
   * (riscado): os dois primeiros valores do card NÃO servem, porque em vários
   * anúncios o segundo número é parcela, não preço cheio.
   */
  {
    slug: "kit-growth-whey-protein-concentrado-natural-1kg--cre",
    url: "https://meli.la/1a7V8kT",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Concentrado Natural 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_664805-MLB99846326143_112025-E--kit-growth-whey-protein-concentrado-natural-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 220.8,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-sorvete-de-creme-1kg--creati",
    url: "https://meli.la/128s1DG",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Sorvete De Creme 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_745731-MLB99361569224_112025-E--kit-growth-whey-protein-sorvete-de-creme-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 220.8,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-milkshake-chocolate-1kg--cre",
    url: "https://meli.la/1HCPB3Q",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Milkshake Chocolate 1kg + Creatina Monohidratada 250g Sem Sabor",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_694106-MLB99843864481_112025-E--kit-growth-whey-protein-milkshake-chocolate-1kg--creatina-monohidratada-250g-sem-sabor.webp",
    price: 220.8,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-concentrado-leite-em-po-1kg",
    url: "https://meli.la/2QLWSmC",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Concentrado Leite Em Pó 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_607432-MLB99845029385_112025-E--kit-growth-whey-protein-concentrado-leite-em-po-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 216.08,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-basic-chocolate-1kg--creatin",
    url: "https://meli.la/2xGzKAk",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Basic Chocolate 1kg + Creatina Monohidratada 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_766763-MLB102163177100_122025-E--kit-growth-whey-protein-basic-chocolate-1kg--creatina-monohidratada-250g.webp",
    price: 107.16,
    originalPrice: 112.8,
  },
  {
    slug: "kit-growth-whey-protein-basic-natural-1kg--creatina",
    url: "https://meli.la/22eBq8v",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Basic Natural 1kg + Creatina Monohidratada 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_903487-MLB102163767830_122025-E--kit-growth-whey-protein-basic-natural-1kg--creatina-monohidratada-250g.webp",
    price: 99.89,
    originalPrice: 112.8,
  },
  {
    slug: "kit-growth-whey-protein-cookies-and-cream-1kg--creat",
    url: "https://meli.la/1vhkPJs",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Cookies And Cream 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_616644-MLB99363074942_112025-E--kit-growth-whey-protein-cookies-and-cream-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 220.8,
  },
  {
    slug: "kit-growth-whey-protein-baunilha-1kg--creatina-monoh",
    url: "https://meli.la/12SCvHV",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Baunilha 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_844212-MLB99845030089_112025-E--kit-growth-whey-protein-baunilha-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 220.8,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-baunilha-1kg--multivitaminic",
    url: "https://meli.la/1zjQNXu",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Baunilha 1kg + Multivitamínico 120 Cáps + Creatina Monohidratada 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_742606-MLB99899081044_122025-E--kit-growth-whey-protein-baunilha-1kg--multivitaminico-120-caps--creatina-monohidratada-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-milkshake-chocolate-1kg--mul",
    url: "https://meli.la/1JX1YSH",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Milkshake Chocolate 1kg + Multivitamínico 120 Cáps + Creatina 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_782651-MLB99898398824_122025-E--kit-growth-whey-protein-milkshake-chocolate-1kg--multivitaminico-120-caps--creatina-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-concentrado-chocolate-branco-1kg--cr",
    url: "https://meli.la/11n7frh",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Concentrado Chocolate Branco 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_976821-MLB99362610288_112025-E--kit-growth-whey-concentrado-chocolate-branco-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 230.2,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-doce-de-leite-1kg--multivita",
    url: "https://meli.la/1nCHGo4",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Doce De Leite 1kg + Multivitamínico 120 Cáps + Creatina Monohidratada 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_944098-MLB100386521771_122025-E--kit-growth-whey-protein-doce-de-leite-1kg--multivitaminico-120-caps--creatina-monohidratada-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-cookies-and-cream-1kg--cr-2",
    url: "https://meli.la/25ga9Bj",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Cookies And Cream 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_799264-MLB99359401638_112025-E--kit-growth-whey-protein-cookies-and-cream-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-leite-em-po-1kg--multivitami",
    url: "https://meli.la/1DN5vDJ",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Leite Em Pó 1kg + Multivitamínico 120 Cáps + Creatina Monohidratada 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_909431-MLB99898971466_122025-E--kit-growth-whey-protein-leite-em-po-1kg--multivitaminico-120-caps--creatina-monohidratada-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-doce-de-leite-1kg--creatina",
    url: "https://meli.la/238KAfu",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Doce De Leite 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_880740-MLB99361727498_112025-E--kit-growth-whey-protein-doce-de-leite-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 220.8,
  },
  {
    slug: "kit-growth-whey-protein-concentrado-morango-1kg--cre",
    url: "https://meli.la/1ES6CiE",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Concentrado Morango 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_755607-MLB99361946974_112025-E--kit-growth-whey-protein-concentrado-morango-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 220.8,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-morango-1kg--multivitaminico",
    url: "https://meli.la/1TBRgr5",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Morango 1kg + Multivitamínico 120 Cáps + Creatina Monohidratada 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_800265-MLB100386847551_122025-E--kit-growth-whey-protein-morango-1kg--multivitaminico-120-caps--creatina-monohidratada-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-sorvete-de-creme-1kg--multiv",
    url: "https://meli.la/2Rr1SSM",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Sorvete De Creme 1kg + Multivitamínico 120 Cáps + Creatina 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_822338-MLB99898840560_122025-E--kit-growth-whey-protein-sorvete-de-creme-1kg--multivitaminico-120-caps--creatina-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-capuccino-1kg--multivitamini",
    url: "https://meli.la/1TxUFre",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Capuccino 1kg + Multivitamínico 120 Cáps + Creatina Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_687207-MLB99901001254_122025-E--kit-growth-whey-protein-capuccino-1kg--multivitaminico-120-caps--creatina-sem-sabor-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-natural-1kg--creatina-creapu",
    url: "https://meli.la/1dPpXTE",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Natural 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_718039-MLB99842880189_112025-E--kit-growth-whey-protein-natural-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-concentrado-chocolate-branco-1kg--2",
    url: "https://meli.la/2oxU6kK",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Concentrado Chocolate Branco 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_735623-MLB99359503446_112025-E--kit-growth-whey-concentrado-chocolate-branco-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-baunilha-1kg--creatina-creap",
    url: "https://meli.la/2vnACGU",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Baunilha 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_671024-MLB99359401154_112025-E--kit-growth-whey-protein-baunilha-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
  },
  {
    slug: "kit-growth-whey-protein-natural-1kg--multivitaminico",
    url: "https://meli.la/1xoxcZW",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Natural 1kg + Multivitamínico 120 Cáps + Creatina Monohidratada 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_860653-MLB100389035797_122025-E--kit-growth-whey-protein-natural-1kg--multivitaminico-120-caps--creatina-monohidratada-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-capuccino-1kg--creatina-mono",
    url: "https://meli.la/2vYJMnz",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Capuccino 1kg + Creatina Monohidratada 250g Sem Sabor",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_725462-MLB99362738914_112025-E--kit-growth-whey-protein-capuccino-1kg--creatina-monohidratada-250g-sem-sabor.webp",
    price: 228.09,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-sorvete-de-creme-1kg--cre-2",
    url: "https://meli.la/2kdGXsv",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Sorvete De Creme 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_991447-MLB99842787671_112025-E--kit-growth-whey-protein-sorvete-de-creme-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-doce-de-leite-1kg--creati-2",
    url: "https://meli.la/2ZvZRb7",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Doce De Leite 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_951298-MLB99359507338_112025-E--kit-growth-whey-protein-doce-de-leite-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 269.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-milkshake-de-chocolate-1kg",
    url: "https://meli.la/1epuisE",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Milkshake De Chocolate 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_705914-MLB99841873251_112025-E--kit-growth-whey-protein-milkshake-de-chocolate-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-chocolate-1kg--creatina-mono",
    url: "https://meli.la/1ZMfBA6",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Chocolate 1kg + Creatina Monohidratada Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_753768-MLB99843191481_112025-E--kit-growth-whey-protein-chocolate-1kg--creatina-monohidratada-sem-sabor-250g.webp",
    price: 230.2,
    originalPrice: 244.8,
  },
  {
    slug: "kit-growth-whey-protein-cookies-and-cream-1kg--multi",
    url: "https://meli.la/2nzqrCW",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Cookies And Cream 1kg + Multivitamínico 120 Cáps + Creatina 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_984577-MLB99900871918_122025-E--kit-growth-whey-protein-cookies-and-cream-1kg--multivitaminico-120-caps--creatina-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-capuccino-1kg--creatina-crea",
    url: "https://meli.la/12R3szz",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Capuccino 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_801058-MLB99359521756_112025-E--kit-growth-whey-protein-capuccino-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-creatina-monohidratada-250g--multivitamin",
    url: "https://meli.la/1Z7TLv2",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Creatina Monohidratada 250g + Multivitamínico 120 Cáps + Pré-treino Haze Uva 300g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_903760-MLB99984262752_122025-E--kit-growth-creatina-monohidratada-250g--multivitaminico-120-caps--pretreino-haze-uva-300g.webp",
    price: 179.9,
    originalPrice: 192.7,
  },
  {
    slug: "kit-growth-whey-chocolate-branco-1kg--multivitaminic",
    url: "https://meli.la/11rD85y",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Chocolate Branco 1kg + Multivitamínico 120 Cáps. + Creatina Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_959008-MLB99901245334_122025-E--kit-growth-whey-chocolate-branco-1kg--multivitaminico-120-caps--creatina-sem-sabor-250g.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
  {
    slug: "kit-growth-whey-protein-morango-1kg--creatina-creapu",
    url: "https://meli.la/2wqWjPr",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Morango 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_662049-MLB99359806238_112025-E--kit-growth-whey-protein-morango-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-concentrado-leite-em-po-1-2",
    url: "https://meli.la/2aPuAsv",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Concentrado Leite Em Pó 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_917485-MLB99359400460_112025-E--kit-growth-whey-protein-concentrado-leite-em-po-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 281.9,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-concentrado-chocolate-1kg--c",
    url: "https://meli.la/2yyqfS1",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Concentrado Chocolate 1kg + Creatina Creapure Sem Sabor 250g",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_614429-MLB99259582214_112025-E--kit-growth-whey-protein-concentrado-chocolate-1kg--creatina-creapure-sem-sabor-250g.webp",
    price: 313.13,
    originalPrice: 330.8,
  },
  {
    slug: "kit-growth-whey-protein-chocolate-1kg--multivitamini",
    url: "https://meli.la/1Sxkaie",
    platform: "MERCADO_LIVRE",
    categories: ["Kits Growth", "Fitness"],
    kind: "lista",
    verifiedAt: "2026-08-25",
    title: "Kit Growth: Whey Protein Chocolate 1kg + Multivitamínico 120 Cáps. + Creatina 250g Sem Sabor",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_886448-MLB100384425217_122025-E--kit-growth-whey-protein-chocolate-1kg--multivitaminico-120-caps--creatina-250g-sem-sabor.webp",
    price: 254.9,
    originalPrice: 297.7,
  },
];

/**
 * Itens que saíram do ar — guardados para poder VOLTAR.
 *
 * Quando um anúncio morre (o link de afiliado passa a cair em
 * /social/<user>/lists, sem botão "Ir para produto"), o item some do site para
 * ninguém clicar em nada. Mas a curadoria por trás dele não se perde: fica
 * aqui, com o motivo, o que entrou no lugar e — quando existe — o candidato
 * já mapeado para reativar.
 *
 * Para trazer de volta: confirmar o anúncio pelo método do container, gerar
 * link de afiliado novo e mover a entrada de volta para `links` acima,
 * MANTENDO o slug original (é a chave do histórico de cliques no analytics).
 */
export interface RetiredLink {
  slug: string;
  /** Último link conhecido — pode estar morto, serve de rastro */
  url: string;
  title: string;
  image?: string;
  price?: number;
  categories: string[];
  /** Review original, preservado para quando o item voltar */
  review?: string;
  retiredAt: string;
  reason: string;
  /** Slug do item que ficou no lugar, quando houve substituição */
  replacedBy?: string;
  /** Candidato já pesquisado para reativar, com o que falta fazer */
  candidate?: string;
}

export const retiredLinks: RetiredLink[] = [
  {
    slug: "fita-led-neon-5m-rgb-ip65-bluetooth",
    url: "https://meli.la/2dJPm3m",
    title: "Fita LED Neon 5m RGB IP65 À Prova d'Água Bluetooth + Fonte",
    image:
      "https://http2.mlstatic.com/D_NQ_NP_962393-MLB110663147588_052026-O.webp",
    price: 76,
    categories: ["Casa"],
    retiredAt: "2026-08-09",
    reason:
      "Anúncio saiu do ar e o item não tinha oferta alternativa cadastrada.",
    candidate:
      "Nenhum equivalente honesto até agora: na Amazon a fita NEON de 5m custa R$ 193 (2,5x) e a de R$ 42 não é neon, é fita comum. Procurar neon 5m IP65 no ML com preferência por Full.",
  },
  {
    slug: "straps-fitness-rudel-h-8-204-preto-ml",
    url: "https://meli.la/2Y5nFAX",
    title: "Straps Fitness Rudel H-8 204 Preto (anúncio ML)",
    price: 35.89,
    categories: ["Fitness"],
    review:
      "Uso com menos frequência, mas é muito bom — ajuda bastante, só não pode virar muleta.",
    retiredAt: "2026-09-18",
    reason:
      "Anúncio do ML morreu. O item continua no site pela Shopee (mesmo produto, mesmo preço), então só o link do ML foi aposentado.",
    replacedBy: "straps-fitness-rudel-h-8-204-preto",
    candidate:
      "Strap Rudel H8 (MLB4687812325) a R$ 25 no ML — mesmo modelo e R$ 10 mais barato. Falta gerar link de afiliado e reconferir pelo container.",
  },
];
